/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainRouteRouteImport } from './routes/__main/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _mainIndexRouteImport } from './routes/__main/index'
import { Route as _mainCreateTestRouteImport } from './routes/__main/create-test'
import { Route as _authSignupRouteImport } from './routes/__auth/signup'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'

const _mainRouteRoute = _mainRouteRouteImport.update({
  id: '/__main',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainIndexRoute = _mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainCreateTestRoute = _mainCreateTestRouteImport.update({
  id: '/create-test',
  path: '/create-test',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _authSignupRoute = _authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainIndexRoute
  '/signin': typeof _authSigninRoute
  '/signup': typeof _authSignupRoute
  '/create-test': typeof _mainCreateTestRoute
}
export interface FileRoutesByTo {
  '/': typeof _mainIndexRoute
  '/signin': typeof _authSigninRoute
  '/signup': typeof _authSignupRoute
  '/create-test': typeof _mainCreateTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__main': typeof _mainRouteRouteWithChildren
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/signup': typeof _authSignupRoute
  '/__main/create-test': typeof _mainCreateTestRoute
  '/__main/': typeof _mainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signup' | '/create-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/create-test'
  id:
    | '__root__'
    | '/__auth'
    | '/__main'
    | '/__auth/signin'
    | '/__auth/signup'
    | '/__main/create-test'
    | '/__main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _mainRouteRoute: typeof _mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/create-test': {
      id: '/__main/create-test'
      path: '/create-test'
      fullPath: '/create-test'
      preLoaderRoute: typeof _mainCreateTestRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__auth/signup': {
      id: '/__auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof _authSignupRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authSigninRoute: typeof _authSigninRoute
  _authSignupRoute: typeof _authSignupRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authSigninRoute: _authSigninRoute,
  _authSignupRoute: _authSignupRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _mainRouteRouteChildren {
  _mainCreateTestRoute: typeof _mainCreateTestRoute
  _mainIndexRoute: typeof _mainIndexRoute
}

const _mainRouteRouteChildren: _mainRouteRouteChildren = {
  _mainCreateTestRoute: _mainCreateTestRoute,
  _mainIndexRoute: _mainIndexRoute,
}

const _mainRouteRouteWithChildren = _mainRouteRoute._addFileChildren(
  _mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _mainRouteRoute: _mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
